import asyncio
import sys
import os

# Add the project root to sys.path
sys.path.append(os.getcwd())

from core.autonomy_kernel import AutonomyKernel
from rae_contracts import RiskClass, TaskState

class MockBridge:
    def log_decision(self, action, reasoning, payload):
         print(f"🌉 [Bridge] {action}: {reasoning}")
    def save_event(self, text, layer="episodic"):
         print(f"📝 [Memory] {text}")

async def run_integration_test():
    bridge = MockBridge()
    kernel = AutonomyKernel(bridge=bridge, repo_root=".")

    print("\n=== CASE 1: R0 Read-Only (Should bypass MCTS planning) ===")
    receipt_r0 = await kernel.execute_task(
        goal_id="g-r0",
        task_id="t-r0",
        intent="Analyze index.css structure",
        payload={}
    )
    print(f"Risk Class: {receipt_r0.risk_class}")
    print(f"Plan Transition State: {receipt_r0.state_transitions[4].to_state} with reason: '{receipt_r0.state_transitions[4].reason}'")
    assert "cognitive_plan_meta" not in receipt_r0.state_transitions[4].reason.lower()

    print("\n=== CASE 2: R3 Pull Request (Should trigger MCTS planning) ===")
    payload_r3 = {}
    receipt_r3 = await kernel.execute_task(
        goal_id="g-r3",
        task_id="t-r3",
        intent="Refactor code and create a pull request to develop",
        payload=payload_r3
    )
    print(f"Risk Class: {receipt_r3.risk_class}")
    print(f"Plan Transition State: {receipt_r3.state_transitions[4].to_state} with reason: '{receipt_r3.state_transitions[4].reason}'")
    print(f"Selected Cognitive Branch: {payload_r3.get('selected_cognitive_branch')}")
    print(f"Win Probability: {payload_r3.get('cognitive_plan_meta', {}).get('win_probability')}")
    assert "selected_cognitive_branch" in payload_r3
    assert payload_r3["cognitive_plan_meta"]["win_probability"] > 0.0

    print("\n=== CASE 3: R3 Database Refactoring (Should trigger MCTS planning with database hypotheses) ===")
    payload_db = {}
    receipt_db = await kernel.execute_task(
        goal_id="g-db",
        task_id="t-db",
        intent="Refactor database adapter and commit to develop branch",
        payload=payload_db
    )
    print(f"Risk Class: {receipt_db.risk_class}")
    print(f"Plan Transition State: {receipt_db.state_transitions[4].to_state} with reason: '{receipt_db.state_transitions[4].reason}'")
    print(f"Selected Cognitive Branch: {payload_db.get('selected_cognitive_branch')}")
    print(f"Win Probability: {payload_db.get('cognitive_plan_meta', {}).get('win_probability')}")
    assert "selected_cognitive_branch" in payload_db
    
    # Print the branches generated by MCTS/ToT
    print("\nGenerated Hypotheses & Viability:")
    for branch in payload_db["cognitive_plan_meta"]["branches"]:
        star = "*" if branch["is_selected"] else " "
        print(f" [{star}] {branch['name']} - Score: {branch['viability_score']}")
        print(f"     Critique Summary: {branch['critique_feedback'].splitlines()[1]}")

    print("\n✅ All integration tests passed successfully!")

if __name__ == "__main__":
    asyncio.run(run_integration_test())
